# Form implementation generated from reading ui file 'ProjectPart1.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.topLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.topLabel.setGeometry(QtCore.QRect(100, 20, 600, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.topLabel.setFont(font)
        self.topLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.topLabel.setWordWrap(True)
        self.topLabel.setObjectName("topLabel")
        self.clearButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(300, 510, 85, 26))
        self.clearButton.setObjectName("clearButton")
        self.submitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(420, 510, 85, 26))
        self.submitButton.setObjectName("submitButton")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(200, 150, 400, 120))
        self.lineEdit.setObjectName("lineEdit")
        self.errorLabelOutput = QtWidgets.QLabel(parent=self.centralwidget)
        self.errorLabelOutput.setGeometry(QtCore.QRect(250, 340, 300, 80))
        self.errorLabelOutput.setFont(font)
        self.errorLabelOutput.setWordWrap(True)
        self.errorLabelOutput.setText("")
        self.errorLabelOutput.setObjectName("errorLabelOutput")
        self.addRadio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.addRadio.setGeometry(QtCore.QRect(140, 470, 90, 18))
        self.addRadio.setObjectName("addRadio")
        self.subtractRadio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.subtractRadio.setGeometry(QtCore.QRect(240, 470, 90, 18))
        self.subtractRadio.setObjectName("subtractRadio")
        self.multiplyRadio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.multiplyRadio.setGeometry(QtCore.QRect(350, 470, 90, 18))
        self.multiplyRadio.setObjectName("multiplyRadio")
        self.divideRadio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.divideRadio.setGeometry(QtCore.QRect(460, 470, 90, 18))
        self.divideRadio.setObjectName("divideRadio")
        self.chooseRadio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.chooseRadio.setGeometry(QtCore.QRect(560, 470, 90, 18))
        self.chooseRadio.setObjectName("chooseRadio")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.topLabel.setText(_translate("MainWindow", "Input numbers into the text box seperated by spaces to compute with the functions selected below."))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.submitButton.setText(_translate("MainWindow", "Submit"))
        self.addRadio.setText(_translate("MainWindow", "Add"))
        self.subtractRadio.setText(_translate("MainWindow", "Subtract"))
        self.multiplyRadio.setText(_translate("MainWindow", "Multiply"))
        self.divideRadio.setText(_translate("MainWindow", "Divide"))
        self.chooseRadio.setText(_translate("MainWindow", "Choose One!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
